Added support for user attributes
permitio/permit-fe-sdk pull request #7
Opened 2023-10-20 18:27 UTC by filipermit

2023-10-22 08:26 UTC, obsd requested changes
I think you should add it near the loggedInUser as well
```
export const Permit = ({ loggedInUser, backendUrl, defaultAnswerIfNotExist = false }: PermitProps) => {
  if (!loggedInUser) {
    throw new Error('loggedInUser is required');
  }
```

2023-11-01 08:58 UTC, filipermit commented
<img width="456" alt="image" src="https://github.com/permitio/permit-fe-sdk/assets/109458126/294e0a84-6689-45f9-bf25-141a507fc2ab">

2023-11-07 14:58 UTC, obsd approved these changes

2023-11-07 15:05 UTC, obsd commented on demo_server/server.ts
> +			const { resource, action, userAttributes, resourceAttributes } = resourceAndAction;
I would change the resourceAndAction to checkParams or something

2023-11-10 15:43 UTC, merged